[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "hookmeup"
author = "Daniel Moch"
author-email = "daniel@danielmoch.com"
home-page = "https://github.com/djmoch/hookmeup"
description-file = "README.md"
classifiers = ["License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Version Control :: Git"]
requires-python=">=3.5"
dev-requires = ['pytest', 'pytest-cov', 'pytest-pylint', 'pytest-mock']

[tool.flit.scripts]
hookmeup = "hookmeup:main"
